### ISSUE TITLE
Opera browser - Site doesn't load

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#203]
Someone reported they get this blank screen on Opera.
![image](https://user-images.githubusercontent.com/93257509/161384259-93d188d6-6587-4246-9ee4-c151e73aede4.png)

Note: Kubsy uses a version of Opera called Opera GX and doesn't get this issue.

**Comment by rr-** [comment]
This ticket is nonactionable. At minimum it requires

- Browser version
- Platform
- Platform version
- Console logs (f12 + refresh)

**Comment by Klona13** [comment]
From dinne:
Browser Version:  85.0.4341.47
Platform:   win 7
Platform version:  SP1 ultimate 
```
react-dom.production.min.js:216 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:327248
    at Dl (https://trcustoms.org/static/js/main.f9e508e8.js:2:199774)
    at t.unstable_runWithPriority (https://trcustoms.org/static/js/main.f9e508e8.js:2:279420)
    at Hi (https://trcustoms.org/static/js/main.f9e508e8.js:2:140093)
    at Rl (https://trcustoms.org/static/js/main.f9e508e8.js:2:199235)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:199146
    at I (https://trcustoms.org/static/js/main.f9e508e8.js:2:278479)
    at MessagePort.x.port1.onmessage (https://trcustoms.org/static/js/main.f9e508e8.js:2:277201)
cu @ react-dom.production.min.js:216
scheduler.production.min.js:12 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:327248
    at Dl (https://trcustoms.org/static/js/main.f9e508e8.js:2:199774)
    at t.unstable_runWithPriority (https://trcustoms.org/static/js/main.f9e508e8.js:2:279420)
    at Hi (https://trcustoms.org/static/js/main.f9e508e8.js:2:140093)
    at Rl (https://trcustoms.org/static/js/main.f9e508e8.js:2:199235)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:199146
    at I (https://trcustoms.org/static/js/main.f9e508e8.js:2:278479)
    at MessagePort.x.port1.onmessage (https://trcustoms.org/static/js/main.f9e508e8.js:2:277201)
2query.js:356 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.getAccessToken (https://trcustoms.org/static/js/main.f9e508e8.js:2:309238)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:310521
    at c (https://trcustoms.org/static/js/main.f9e508e8.js:2:270244)
    at Generator._invoke (https://trcustoms.org/static/js/main.f9e508e8.js:2:270032)
    at Generator.next (https://trcustoms.org/static/js/main.f9e508e8.js:2:270673)
    at fe (https://trcustoms.org/static/js/main.f9e508e8.js:2:305178)
    at a (https://trcustoms.org/static/js/main.f9e508e8.js:2:305382)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:305443
    at new Promise (<anonymous>)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:305322
onError @ query.js:356
AuthService.ts:30 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.getAccessToken (https://trcustoms.org/static/js/main.f9e508e8.js:2:309238)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:315626
    at c (https://trcustoms.org/static/js/main.f9e508e8.js:2:270244)
    at Generator._invoke (https://trcustoms.org/static/js/main.f9e508e8.js:2:270032)
    at Generator.next (https://trcustoms.org/static/js/main.f9e508e8.js:2:270673)
    at fe (https://trcustoms.org/static/js/main.f9e508e8.js:2:305178)
    at a (https://trcustoms.org/static/js/main.f9e508e8.js:2:305382)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:305443
    at new Promise (<anonymous>)
    at Object.<anonymous> (https://trcustoms.org/static/js/main.f9e508e8.js:2:305322)
AuthService.ts:30 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.getAccessToken (https://trcustoms.org/static/js/main.f9e508e8.js:2:309238)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:310521
    at c (https://trcustoms.org/static/js/main.f9e508e8.js:2:270244)
    at Generator._invoke (https://trcustoms.org/static/js/main.f9e508e8.js:2:270032)
    at Generator.next (https://trcustoms.org/static/js/main.f9e508e8.js:2:270673)
    at fe (https://trcustoms.org/static/js/main.f9e508e8.js:2:305178)
    at a (https://trcustoms.org/static/js/main.f9e508e8.js:2:305382)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:305443
    at new Promise (<anonymous>)
    at https://trcustoms.org/static/js/main.f9e508e8.js:2:305322
```
